name: Remove deleted branch from launchermeta
on:
  delete:

jobs:
  remove_deleted_branch:
    runs-on: ubuntu-latest
    name: Remove deleted branch
    if: github.event.ref_type == 'branch'

    steps:
      - name: Delete branch from launchermeta
        run: |
          git push origin --delete "${{ github.event.ref }}" || true;
