name: Env persistence test

on:
  pull_request:
  issues:
    types:
      - opened
      - transferred

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.SAUCE_USERNAME }}

jobs:
  env-persistence:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install
        run: npm install

      - name: another one
        uses: ./
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.SAUCE_USERNAME }}

      - name: Run a command
        env:
          MY_ENV_VAR: "Hello, world!"
        run: echo $MY_ENV_VAR

      - name: Run another command
        run: echo $MY_ENV_VAR

      - name: Set an environment variable
        run: echo "MY_ENV_VAR=Hello, world!" >> $GITHUB_ENV

      - name: Run a command
        run: echo $MY_ENV_VAR

      - name: test
        run: echo $NX_CLOUD_ACCESS_TOKEN
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.SAUCE_USERNAME }}

      - name: bad
        run: npm install

      - name: url
        run: echo ${{ github.event.pull_request.html_url }}

      - name: dog
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}

      - name: dog
        run: echo The Title of your PR is ${{ github.event.pull_request.body }}
